### ISSUE TITLE
One tokenomics test is failing on main

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13188]
### Describe the bug

```
  tokenomics: proofReward
duplicate definition - L1_BLOCK_NUMBER()
duplicate definition - L1_HALT_CONDITION()
duplicate definition - L1_ID()
-------------------
{
  to: '0x6732c278C58FC90542cce498981844A073D693d7',
  from: '0xDf08F82De32B8d460adbE8D72043E3a7e25A3B39',
  contractAddress: null,
  transactionIndex: 0,
  gasUsed: BigNumber { value: "314732" },
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000008000000004000000000000000000000000002000040000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000800000000000000000000000000000000',
  blockHash: '0x967b92396104096c4819a5ee42c75067da846565602178e13d545da63a130bca',
  transactionHash: '0x75a0be7dd0668b3dfbe18eb4dff47e881f7e544a41c6b9c1e718cff0820a32aa',
  logs: [
    {
      transactionIndex: 0,
      blockNumber: 32,
      transactionHash: '0x75a0be7dd0668b3dfbe18eb4dff47e881f7e544a41c6b9c1e718cff0820a32aa',
      address: '0x6732c278C58FC90542cce498981844A073D693d7',
      topics: [Array],
      data: '0x5fd05791fba46aeffcca8ef54b11f7e3a1ccf9557a598fe12005808e022cde8fe0f440818bc717efd750a13f0d1201f1166aae9c5cbba1f51bd27645dc6e96350000000000000000000000000000000000000000000000000000000063f1ff610000000000000000000000000000000000000000000000000000000063f1ff61000000000000000000000000af9dc2115ea050db0d73610dced0e9244d10ea52',
      logIndex: 0,
      blockHash: '0x967b92396104096c4819a5ee42c75067da846565602178e13d545da63a130bca'
    }
  ],
  blockNumber: 32,
  confirmations: 5,
  cumulativeGasUsed: BigNumber { value: "314732" },
  effectiveGasPrice: BigNumber { value: "240751421" },
  status: 1,
  type: 0,
  byzantium: true,
  events: [
    {
      transactionIndex: 0,
      blockNumber: 32,
      transactionHash: '0x75a0be7dd0668b3dfbe18eb4dff47e881f7e544a41c6b9c1e718cff0820a32aa',
      address: '0x6732c278C58FC90542cce498981844A073D693d7',
      topics: [Array],
      data: '0x5fd05791fba46aeffcca8ef54b11f7e3a1ccf9557a598fe12005808e022cde8fe0f440818bc717efd750a13f0d1201f1166aae9c5cbba1f51bd27645dc6e96350000000000000000000000000000000000000000000000000000000063f1ff610000000000000000000000000000000000000000000000000000000063f1ff61000000000000000000000000af9dc2115ea050db0d73610dced0e9244d10ea52',
      logIndex: 0,
      blockHash: '0x967b92396104096c4819a5ee42c75067da846565602178e13d545da63a130bca',
      args: [Array],
      decode: [Function (anonymous)],
      event: 'BlockProven',
      eventSignature: 'BlockProven(uint256,bytes32,bytes32,uint64,uint64,address)',
      removeListener: [Function (anonymous)],
      getBlock: [Function (anonymous)],
      getTransaction: [Function (anonymous)],
      getTransactionReceipt: [Function (anonymous)]
    }
  ]
}
prove error Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4", transaction={"hash":"0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4","type":0,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0xDf08F82De32B8d460adbE8D72043E3a7e25A3B39","gasPrice":{"type":"BigNumber","hex":"0x0dba7fc9"},"gasLimit":{"type":"BigNumber","hex":"0x0f4240"},"to":"0x6732c278C58FC90542cce498981844A073D693d7","value":{"type":"BigNumber","hex":"0x00"},"nonce":33,"data":"0x8ed7b3be00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000740000000000000000000000000000000000000000000000000000000000000076000000000000000000000000000000000000000000000000000000000000006c0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000002200000000000000000000000005ae2dd0204dd191aa01fb5cea5b570c4722cfc34000000000000000000000000000000000000000000000000000000000000052000000000000000000000000000000000000000000000000000000000000006600000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e2fd12a343d91994481f3befb6b87d6824c1546228ec026fde72052609f1ad092000000000000000000000000c014ba5ec014ba5ec014ba5ec014ba5ec014ba5ed000f126458d08dd984f2efe2a9b9e8f89bab54743ae4de830709d5f11a2208e44663b06e0b3bf0f0cdc6e9c06362d2f72f8f5295e218096f2b79aece1547a2b00000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000001c9c3800000000000000000000000000000000000000000000000000000000063f1ff61000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005fd05791fba46aeffcca8ef54b11f7e3a1ccf9557a598fe12005808e022cde8f1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347000000000000000000000000c014ba5ec014ba5ec014ba5ec014ba5ec014ba5ea80e9385c4c3ffcf83eb089864bd81035367c7286643bfa5c84635c3f8a5a35453b786b2c0c3b9a1d36d42a7e6c96ba01609dc9887cd2f79b00daf4906a43cb6f78dfb743fbd92ade140711c8bbc542b5e307f0ab7984eff35d751969fe57efa00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002010000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000001c9c38000000000000000000000000000000000000000000000000000000000000052080000000000000000000000000000000000000000000000000000000063f1ff6200000000000000000000000000000000000000000000000000000000000002e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042000000000000000000000000000000000000000000000000000000001ffcec5700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","r":"0x125b40b15eeffcd8c3c323029391c5d94e17015cdcd941ad052fba4b6bcb3f52","s":"0x39b9e76a941f57fb25fe632c00d2cd79087ea1bc442be74bec640e126f68341d","v":2710,"creates":null,"chainId":1337}, receipt={"to":"0x6732c278C58FC90542cce498981844A073D693d7","from":"0xDf08F82De32B8d460adbE8D72043E3a7e25A3B39","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x035a66"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x0f0e6f1eeaa0607936b4d95aac4a4ca4725680f482ca3cb01f1f4b8d5001004e","transactionHash":"0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4","logs":[],"blockNumber":37,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x035a66"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x0dba7fc9"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1549:24)
    at step (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'transaction failed',
  code: 'CALL_EXCEPTION',
  transactionHash: '0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4',
  transaction: {
    hash: '0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4',
    type: 0,
    accessList: null,
    blockHash: null,
    blockNumber: null,
    transactionIndex: null,
    confirmations: 0,
    from: '0xDf08F82De32B8d460adbE8D72043E3a7e25A3B39',
    gasPrice: BigNumber { value: "230326217" },
    gasLimit: BigNumber { value: "1000000" },
    to: '0x6732c278C58FC90542cce498981844A073D693d7',
    value: BigNumber { value: "0" },
    nonce: 33,
    data: '0x8ed7b3be00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000740000000000000000000000000000000000000000000000000000000000000076000000000000000000000000000000000000000000000000000000000000006c0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000002200000000000000000000000005ae2dd0204dd191aa01fb5cea5b570c4722cfc34000000000000000000000000000000000000000000000000000000000000052000000000000000000000000000000000000000000000000000000000000006600000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e2fd12a343d91994481f3befb6b87d6824c1546228ec026fde72052609f1ad092000000000000000000000000c014ba5ec014ba5ec014ba5ec014ba5ec014ba5ed000f126458d08dd984f2efe2a9b9e8f89bab54743ae4de830709d5f11a2208e44663b06e0b3bf0f0cdc6e9c06362d2f72f8f5295e218096f2b79aece1547a2b00000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000001c9c3800000000000000000000000000000000000000000000000000000000063f1ff61000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005fd05791fba46aeffcca8ef54b11f7e3a1ccf9557a598fe12005808e022cde8f1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347000000000000000000000000c014ba5ec014ba5ec014ba5ec014ba5ec014ba5ea80e9385c4c3ffcf83eb089864bd81035367c7286643bfa5c84635c3f8a5a35453b786b2c0c3b9a1d36d42a7e6c96ba01609dc9887cd2f79b00daf4906a43cb6f78dfb743fbd92ade140711c8bbc542b5e307f0ab7984eff35d751969fe57efa00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002010000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000001c9c38000000000000000000000000000000000000000000000000000000000000052080000000000000000000000000000000000000000000000000000000063f1ff6200000000000000000000000000000000000000000000000000000000000002e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042000000000000000000000000000000000000000000000000000000001ffcec5700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    r: '0x125b40b15eeffcd8c3c323029391c5d94e17015cdcd941ad052fba4b6bcb3f52',
    s: '0x39b9e76a941f57fb25fe632c00d2cd79087ea1bc442be74bec640e126f68341d',
    v: 2710,
    creates: null,
    chainId: 1337,
    wait: [Function (anonymous)]
  },
  receipt: {
    to: '0x6732c278C58FC90542cce498981844A073D693d7',
    from: '0xDf08F82De32B8d460adbE8D72043E3a7e25A3B39',
    contractAddress: null,
    transactionIndex: 0,
    gasUsed: BigNumber { value: "219750" },
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    blockHash: '0x0f0e6f1eeaa0607936b4d95aac4a4ca4725680f482ca3cb01f1f4b8d5001004e',
    transactionHash: '0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4',
    logs: [],
    blockNumber: 37,
    confirmations: 1,
    cumulativeGasUsed: BigNumber { value: "219750" },
    effectiveGasPrice: BigNumber { value: "230326217" },
    status: 0,
    type: 0,
    byzantium: true
  }
}
    1) asserts that with N provers, where N is config.maxProofsPerForkChoice all provers who submit proofs are paid with decreasing weight from the first prover to the Nth


  0 passing (7s)
  1 failing

  1) tokenomics: proofReward
       asserts that with N provers, where N is config.maxProofsPerForkChoice all provers who submit proofs are paid with decreasing weight from the first prover to the Nth:
     Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4", transaction={"hash":"0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4","type":0,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0xDf08F82De32B8d460adbE8D72043E3a7e25A3B39","gasPrice":{"type":"BigNumber","hex":"0x0dba7fc9"},"gasLimit":{"type":"BigNumber","hex":"0x0f4240"},"to":"0x6732c278C58FC90542cce498981844A073D693d7","value":{"type":"BigNumber","hex":"0x00"},"nonce":33,"data":"0x8ed7b3be00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000740000000000000000000000000000000000000000000000000000000000000076000000000000000000000000000000000000000000000000000000000000006c0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000002200000000000000000000000005ae2dd0204dd191aa01fb5cea5b570c4722cfc34000000000000000000000000000000000000000000000000000000000000052000000000000000000000000000000000000000000000000000000000000006600000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e2fd12a343d91994481f3befb6b87d6824c1546228ec026fde72052609f1ad092000000000000000000000000c014ba5ec014ba5ec014ba5ec014ba5ec014ba5ed000f126458d08dd984f2efe2a9b9e8f89bab54743ae4de830709d5f11a2208e44663b06e0b3bf0f0cdc6e9c06362d2f72f8f5295e218096f2b79aece1547a2b00000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000001c9c3800000000000000000000000000000000000000000000000000000000063f1ff61000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005fd05791fba46aeffcca8ef54b11f7e3a1ccf9557a598fe12005808e022cde8f1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347000000000000000000000000c014ba5ec014ba5ec014ba5ec014ba5ec014ba5ea80e9385c4c3ffcf83eb089864bd81035367c7286643bfa5c84635c3f8a5a35453b786b2c0c3b9a1d36d42a7e6c96ba01609dc9887cd2f79b00daf4906a43cb6f78dfb743fbd92ade140711c8bbc542b5e307f0ab7984eff35d751969fe57efa00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002010000000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000001c9c38000000000000000000000000000000000000000000000000000000000000052080000000000000000000000000000000000000000000000000000000063f1ff6200000000000000000000000000000000000000000000000000000000000002e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042000000000000000000000000000000000000000000000000000000001ffcec5700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","r":"0x125b40b15eeffcd8c3c323029391c5d94e17015cdcd941ad052fba4b6bcb3f52","s":"0x39b9e76a941f57fb25fe632c00d2cd79087ea1bc442be74bec640e126f68341d","v":2710,"creates":null,"chainId":1337}, receipt={"to":"0x6732c278C58FC90542cce498981844A073D693d7","from":"0xDf08F82De32B8d460adbE8D72043E3a7e25A3B39","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x035a66"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x0f0e6f1eeaa0607936b4d95aac4a4ca4725680f482ca3cb01f1f4b8d5001004e","transactionHash":"0x2e093cbc1e23596d1edae3ed883b81ff1835ea13f9053471d3deb044c5b46ed4","logs":[],"blockNumber":37,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x035a66"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x0dba7fc9"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
      at Logger.makeError (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at EthersProviderWrapper.<anonymous> (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1549:24)
      at step (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
      at Object.next (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
      at fulfilled (/Users/d/Projects/taiko/taiko-mono/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by cyberhorsey** [comment]
I will look at this one
