### ISSUE TITLE
Continuous Proposing Behavior in Taiko Alpha-5 Testnet

### ISSUE THREAD

**Issue by BlankerL** [taikoxyz/taiko-mono#15230]
### Describe the bug

Previously, I have successfully proposed and proven hundreds of blocks without any issues. However, I recently encountered a problem after restarting my proposer and prover container approximately 3 hours ago. Since then, my proposer has been continuously proposing without any interruption.

Upon investigating the issue, I checked the logs in my prover relayer, expecting it to reject proposals when reaching its capacity. Surprisingly, it did not follow this expected behavior. The prover relayer simply accepted all proposals with the message `Cleared one temp capacity` (seems removed the previous propose) but did not forward them to the prover rpcd. Some of the `Cleared one temp capacity` will be followed by an error `echo: http: panic serving 10.99.72.8:47796: runtime error: slice bounds out of range [2:1]`. 

Below are the logs from my proposer:

```
INFO [11-18|12:34:49.516] "📝 Propose transactions succeeded"       txs=1
INFO [11-18|12:34:59.624] Start fetching L2 execution engine's transaction pool content 
INFO [11-18|12:34:59.625] Current base fee                         fee=1
INFO [11-18|12:34:59.627] Transactions lists count                 count=1
INFO [11-18|12:34:59.843] Proposer account information             chainHead=4,718,246 nonce=1222
INFO [11-18|12:34:59.947] Attempting to assign prover              endpoint=http://taiko_client_prover_relayer:9876 fee=10 expiry=1,700,312,699
INFO [11-18|12:35:00.084] Prover assigned                          address=<my prover address>endpoint=http://taiko_client_prover_relayer:9876 fee=10 expiry=1,700,312,699
INFO [11-18|12:35:00.188] Prover's deposited taikoTokenBalance     balance=208436080758417779650 address=<my prover address>
INFO [11-18|12:35:15.691] "📝 Propose transactions succeeded"       txs=1
INFO [11-18|12:35:25.808] Start fetching L2 execution engine's transaction pool content 
INFO [11-18|12:35:25.810] Current base fee                         fee=1
INFO [11-18|12:35:25.811] Transactions lists count                 count=1
INFO [11-18|12:35:26.060] Proposer account information             chainHead=4,718,248 nonce=1223
INFO [11-18|12:35:26.175] Attempting to assign prover              endpoint=http://taiko_client_prover_relayer:9876 fee=10 expiry=1,700,312,726
INFO [11-18|12:35:26.295] Prover assigned                          address=<my prover address> endpoint=http://taiko_client_prover_relayer:9876 fee=10 expiry=1,700,312,726
INFO [11-18|12:35:26.399] Prover's deposited taikoTokenBalance     balance=210936080758417779650 address=<my prover address>
INFO [11-18|12:35:38.865] "📝 Propose transactions succeeded"       txs=1
INFO [11-18|12:35:49.118] Start fetching L2 execution engine's transaction pool content 
INFO [11-18|12:35:49.119] Current base fee                         fee=1
INFO [11-18|12:35:49.122] Transactions lists count                 count=1
INFO [11-18|12:35:49.362] Proposer account information             chainHead=4,718,250 nonce=1224
INFO [11-18|12:35:49.467] Attempting to assign prover              endpoint=http://taiko_client_prover_relayer:9876 fee=10 expiry=1,700,312,749
INFO [11-18|12:35:49.587] Prover assigned                          address=<my prover address> endpoint=http://taiko_client_prover_relayer:9876 fee=10 expiry=1,700,312,749
INFO [11-18|12:35:49.693] Prover's deposited taikoTokenBalance     balance=210936080758417779650 address=<my prover address>
INFO [11-18|12:36:02.138] "📝 Propose transactions succeeded"       txs=1
INFO [11-18|12:36:12.241] Start fetching L2 execution engine's transaction pool content 
INFO [11-18|12:36:12.242] Current base fee                         fee=1
INFO [11-18|12:36:12.248] Transactions lists count                 count=1
INFO [11-18|12:36:12.467] Proposer account information             chainHead=4,718,251 nonce=1225
INFO [11-18|12:36:12.573] Attempting to assign prover              endpoint=http://taiko_client_prover_relayer:9876 fee=10 expiry=1,700,312,772
INFO [11-18|12:36:12.693] Prover assigned                          address=<my prover address> endpoint=http://taiko_client_prover_relayer:9876 fee=10 expiry=1,700,312,772
INFO [11-18|12:36:12.802] Prover's deposited taikoTokenBalance     balance=208436080758417779650 address=<my prover address>
INFO [11-18|12:36:25.281] "📝 Propose transactions succeeded"       txs=4
```

Belows are the errors from my prover relayer:

```
INFO [11-18|12:32:25.626] Propose block data                       fee=10 expiry=1,700,312,545
INFO [11-18|12:32:25.746] Prover's deposited taikoTokenBalance     balance=210936080758417779650 address=0xF30dfC26D42337fE1D98BB380799381cb0957E4e
INFO [11-18|12:32:25.746] Cleared one temp capacity                maxCapacity=2 currentCapacityAfterClearing=2 currentUsageAfterClearing=0 tempCapacity=1 tempCapacityUsage=1
echo: http: panic serving 10.99.72.8:47796: runtime error: slice bounds out of range [2:1]
goroutine 737 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0xf8c3e0?, 0xc00003dc68?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/taikoxyz/taiko-client/prover/capacity_manager.(*CapacityManager).clearExpiredTempCapacities(0xc0000dc6e0)
	/taiko-client/prover/capacity_manager/capacity_manager.go:125 +0x445
github.com/taikoxyz/taiko-client/prover/capacity_manager.(*CapacityManager).TakeOneTempCapacity(0xc0000dc6e0)
	/taiko-client/prover/capacity_manager/capacity_manager.go:104 +0x9c
github.com/taikoxyz/taiko-client/prover/server.(*ProverServer).CreateAssignment(0xc000214e00, {0x134a300, 0xc000314140})
	/taiko-client/prover/server/api.go:102 +0x5aa
github.com/labstack/echo/v4.(*Echo).add.func1({0x134a300, 0xc000314140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.11.1/echo.go:582 +0x4b
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x134a300, 0xc000314140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.11.1/middleware/logger.go:120 +0x45c
github.com/taikoxyz/taiko-client/prover/server.(*ProverServer).configureMiddleware.RequestID.RequestIDWithConfig.func1.1({0x134a300, 0xc000314140})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.11.1/middleware/request_id.go:70 +0x112
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000038900, {0x133a610?, 0xc0000fc8c0}, 0xc0003a2000)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.11.1/echo.go:669 +0x399
net/http.serverHandler.ServeHTTP({0x1338280?}, {0x133a610?, 0xc0000fc8c0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0004086c0, {0x133ce80, 0xc0003102d0})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 109
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
```

In my prover rpcd, it is empty without receiving any request to compute proof:

```
[2023-11-18T10:44:00Z INFO  prover::server] Listening on http://0.0.0.0:9000
```

The timestamp might be mismatched because I copied them from the latest logs, but it shows the same when the timestamp aligns.

I appreciate your prompt attention to this matter and would be grateful for any assistance in resolving this bug. If you require additional information or logs, please do not hesitate to ask.

Thank you for your time and assistance.

### Steps to reproduce

N/A

### Additional context

N/A

**Comment by BlankerL** [comment]
After running for 2 hours, and while I was drafting this issue, the prover relayer returned to normal and started to `Take one capacity`.

Here are the logs:
```
INFO [11-18|12:51:26.188] Proposed block                           L1Height=4,718,215 L1Hash=ebfe33..876ca8 BlockID=1,191,396 Removed=false
INFO [11-18|12:51:26.636] Proposed block information               blockID=1,191,396 prover=<my prover address>proposedAt=1,700,310,492
INFO [11-18|12:51:26.636] Proposed block is provable               blockID=1,191,396 prover=<my prover address> proofWindowExpired=false
INFO [11-18|12:51:26.636] Took one capacity                        blockID=1,191,396 maxCapacity=2 currentCapacityAfterTaking=1 currentUsageAfterTaking=1
INFO [11-18|12:51:26.743] Request proof from zkevm-chain proverd service blockID=1,191,396 proposer=<my proposer address> height=1,191,396 hash=59bea8..9b8ab7
INFO [11-18|12:51:26.744] Proof generating                         height=1,191,396 time="861.574µs"
```

I suspect there might still be an issue in the prover relayer's code, but I haven't been able to identify the bug. I am concerned that errors in proposed blocks could potentially lead to the prover being slashed, especially in the production/mainnet stage.

**Comment by d1onys1us** [comment]
@davidtaikocha would you be able to take a look at this or assign to someone? i'm not sure if it is still an issue. if not, we can close the issue.

**Comment by davidtaikocha** [comment]
Closed due to at least its not an issue for A6 anymore
